version: '3.8'
services:
    elasticsearch:
      # network_mode: elastic
        container_name: elasticsearch
        ports:
            - '9200:9200'
            - '9300:9300'
        volumes:
          - type: bind
            source: ./elasticsearch.yml
            target: /usr/share/elasticsearch/config/elasticsearch.yml
        environment:
            - discovery.type=single-node
        image: 'docker.elastic.co/elasticsearch/elasticsearch:8.8.0'
        networks:
            - elastic
    kibana:
      # network_mode: elastic
        container_name: kibana
        ports:
            - '5601:5601'
        volumes:
          - type: bind
            source: ./kibana.yml
            target: /usr/share/kibana/config/kibana.yml
        environment:
            - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
        image: 'docker.elastic.co/kibana/kibana:8.8.0' 
        depends_on:
            - elasticsearch
        networks:
            - elastic 

    nginx:
        container_name: nginx
        image: nginx:alpine
        volumes:
            - ./nginx/log:/var/log/nginx
        ports:
            - "80:80"
        networks:
            - elastic

    logstash:
        container_name: logstash
        volumes:
            - type: bind
              source: ./logstash.yml
              target: /usr/share/logstash/config/logstash.yml
            - type: bind
              source: ./nginx/config
              target: /usr/share/logstash/pipeline
        ports:
            - "5000:5000"
            - "9600:9600"
        expose: 
            - "5044"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        image: 'docker.elastic.co/logstash/logstash:8.8.0'
        networks:
            - elastic
        depends_on:
            - elasticsearch

    filebeat:
        user: root
        container_name: filebeat
        command: --strict.perms=false
        volumes:
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./nginx/log:/var/log/nginx
        image: 'docker.elastic.co/beats/filebeat:8.8.0' 
        depends_on:   
          - elasticsearch
          - logstash
          - kibana
          - nginx
    
        networks:
            - elastic              
networks:
  elastic:
    name: elastic      